### ISSUE TITLE
phantom starting before selenium server

### ISSUE THREAD

**Issue by rebas82** [grantlucas/phantoman#53]
I have in tests/_envs this files:
masterChrome.yml , masterPhantom.yml, produkceChrome.yml, produkceChrome.yml

in my codeception.yml i have:

```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Phantoman
    config:
        Codeception\Extension\Phantoman:
        port: 4445
        suites: [acceptance '(produkcePhantom)', acceptance '(masterPhantom)']
```

When i start codeception as: vendor\bin\codecept run --env masterChrome acceptance --html
phantom starting first, after start phantom, test running in chrome (selenium server).

where is my mistake?
I use last versions (codeception 2.2.4, phantoman 1.1.6,
